# Configuration Netlify pour DietTracker

[build]
  # Répertoire du frontend
  base = "src/frontend"
  
  # Commande de build
  command = "npm run build"
  
  # Dossier de publication
  publish = "dist"

[build.environment]
  # Version Node.js
  NODE_VERSION = "18"

# Redirections pour le React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"