# Configuration Netlify pour DietTracker

[build]
  # Répertoire de base (racine du projet)
  base = ""
  
  # Commande de build depuis la racine
  command = "npm install && npm run build"
  
  # Dossier de publication (relatif à base)
  publish = "src/frontend/dist"

[build.environment]
  # Version Node.js
  NODE_VERSION = "18"

# Redirections pour le React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"